name: sonar-project-workflow
on:
  workflow_dispatch:
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
     
      - name: script
        shell: bash
        run: | 
        
         SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
         echo $SONAR_TOKEN
         ORGANIZATION=${{ vars.ORGANIZATION_NAME }}
         echo $ORGANIZATION
         # VISIBILITY="public"
         NEW_CODE_DEFINITION_TYPE="previous_version"
         # NEW_CODE_DEFINITION_VALUE="previous_version"
        
         # List of project names and keys
         PROJECTS=("test-react12" "test-sonar12" "test-go12")
         PROJECT_KEYS=("test-react-key12" "test-sonar-key12" "test-go-key12")
         for i in "${!PROJECTS[@]}"; do
             PROJECT_NAME="${PROJECTS[$i]}"
             PROJECT_KEY="${PROJECT_KEYS[$i]}"
        
             curl --include \
                  --request POST \
                  -u "$SONAR_TOKEN:" \
                  "https://sonarcloud.io/api/projects/create?organization=$ORGANIZATION&project=$PROJECT_KEY&name=$PROJECT_NAME&newCodeDefinitionType=$NEW_CODE_DEFINITION_TYPE&newCodeDefinitionValue=$NEW_CODE_DEFINITION_VALUE
         done
            
          
                

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
