name: sonar-project-workflow
on:
  workflow_dispatch: 
    inputs:
      project_names:
        description: 'Enter project names as a space-separated list e.g proj1 proj2 proj3'
        required: true
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
     
      - name: script
        shell: bash
        run: | 
        
         SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
         ORGANIZATION=${{ vars.ORGANIZATION_KEY }}
         # VISIBILITY="private"
         NEW_CODE_DEFINITION_TYPE="previous_version"
         NEW_CODE_DEFINITION_VALUE="previous_version"
        
         INPUT_STRING="${{ inputs.project_names }}"
         TRIMMED_STRING="$(echo -e "${INPUT_STRING}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
         IFS=' ' read -r -a PROJECTS <<< "$TRIMMED_STRING"
         echo "Received projects: ${PROJECTS[*]}"
         for i in "${!PROJECTS[@]}"; do
             PROJECT_NAME="${PROJECTS[$i]}"
             PROJECT_KEY="$ORGANIZATION"_"$PROJECT_NAME"
             echo "Creating project: $PROJECT_NAME with key: $PROJECT_KEY"
             curl --include \
                  --request POST \
                  -u "$SONAR_TOKEN:" \
                  "https://sonarcloud.io/api/projects/create?organization=$ORGANIZATION&project=$PROJECT_KEY&name=$PROJECT_NAME&newCodeDefinitionType=$NEW_CODE_DEFINITION_TYPE&newCodeDefinitionValue=$NEW_CODE_DEFINITION_VALUE"
         done
